CommonBoilerPlateEight.Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace CommonBoilerPlateEight.Web.Controllers;

public class BaseController : Controller
{
    public IActionResult SetCulture(string culture)
    {
        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
        );

        return Redirect(Request.Headers["Referer"].ToString());
    }
}

CommonBoilerPlateEight.Web/Controllers/SettingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using CommonBoilerPlateEight.Domain.Interfaces;
using CommonBoilerPlateEight.Web.Extensions;

namespace CommonBoilerPlateEight.Web.Controllers
{
    [Authorize]
    public class SettingController : Controller
    {
        private readonly IApplicationSettingService _settingService;
        public SettingController(IApplicationSettingService settingService)
        {
            _settingService = settingService;
        }
        public async Task<IActionResult> EmailSetup()
        {
            var emailSetupViewModel = await _settingService.GetEmailSettings();
            return View(emailSetupViewModel);
        }
       
        [HttpPost]
        public async Task<IActionResult> EmailSetup(EmailSetupViewModel model)
        {
            await _settingService.SetEmailSettings(model);
            this.NotifySuccess("Saved Successfully");
            return RedirectToAction(nameof(EmailSetup));
        }
    }
}

CommonBoilerPlateEight.Web/Views/Shared/_BlankLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Responsive HTML Admin Dashboard Template based on Bootstrap 5">
    <meta name="author" content="NobleUI">
    <meta name="keywords" content="nobleui, bootstrap, bootstrap 5, bootstrap5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

    <title>Common World</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <!-- End fonts -->
    <!-- core:css -->
    <link rel="stylesheet" href="~/vendors/core/core.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/flatpickr/flatpickr.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/fonts/feather-font/css/iconfont.css">
    <link rel="stylesheet" href="~/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/vendors/datatables.net-bs5/dataTables.bootstrap5.css">
    <link rel="stylesheet" href="~/vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/vendors/spinkit/spinkit.dist.css">

    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- End layout styles -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
    <link rel="shortcut icon" href="~/images/favicon.png" />
</head>
<body>
    <div class="main-wrapper">
        <div class="page-wrapper full-page">
            <div class="page-content d-flex align-items-center justify-content-center">
                @RenderBody()
            </div>
        </div>
    </div>

    <!-- core:js -->
    <script src="~/vendors/core/core.js"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/vendors/flatpickr/flatpickr.min.js"></script>
    <script src="~/vendors/apexcharts/apexcharts.min.js"></script>
    <script src="~/js/sweetalert.js"></script>
    <script src="~/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/vendors/datatables.net-bs5/dataTables.bootstrap5.js"></script>
    <script src="~/vendors/block-ui/block-ui.dist.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/vendors/feather-icons/feather.min.js"></script>
    <script src="~/js/template.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/js/dashboard-light.js"></script>
    <script src="~/js/site.js"></script>
    <!-- End custom js for this page -->
    @await Html.PartialAsync("_notificationPartial")
    @await RenderSectionAsync("Scripts", false)


</body>
</html>    

CommonBoilerPlateEight.Web/Views/Shared/_DeleteModal.cshtml
@* @model DeleteModalViewModel

<div class="modal fade bs-delete-modal" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header alert-danger">
                <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="btn-close"></button>
            </div>
            <div class="modal-body">
              Are You Sure To Delete ?
            </div>
            <div class="modal-footer">
                <form id="deleteForm" method="post" asp-controller="@Model.Controller" asp-action="@Model.Action">
                    <input type="hidden" name="Id" id="DeleteId" />
                    <button type="submit" class="btn btn-danger btn-xs">@_CommonLocalizer["Delete"]</button>
                </form>
                <button type="button" class="btn btn-secondary btn-xs" data-bs-dismiss="modal">@_CommonLocalizer["Cancel"]</button>
            </div>
        </div>
    </div>
</div> *@

CommonBoilerPlateEight.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="@_CommonLocalizer["LanguageCode"]" dir="@_CommonLocalizer["Dir"]">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="CommonBoilerPlateEight">
    <meta name="author" content="CommonBoilerPlateEight">
    <meta name="keywords" content="CommonBoilerPlateEight">

    <title>CommonBoilerPlateEight</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <!-- End fonts -->
    <!-- core:css -->
    <link rel="stylesheet" href="~/vendors/core/core.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link href="~/vendors/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/vendors/flatpickr/flatpickr.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/fonts/feather-font/css/iconfont.css">
    <link rel="stylesheet" href="~/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/vendors/datatables.net-bs5/datatables.bootstrap5.dist.css">
    <link rel="stylesheet" href="~/vendors/datatables.net-bs5/buttons.bootstrap5.dist.css">
    <link rel="stylesheet" href="~/vendors/datatables.net-bs5/responsive.bootstrap5.dist.css">
    <link rel="stylesheet" href="~/fonts/fontawesome.dist.css">
    <link rel="stylesheet" href="~/vendors/spinkit/spinkit.dist.css">
    <link rel="stylesheet" href="~/vendors/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/vendors/flatpickr/flatpickr.min.css">

    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/css/@(_CommonLocalizer["CoreStyle"]).css" asp-append-version="true">
    <!-- End layout styles -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
    <link rel="shortcut icon" href="~/images/favicon.png" />
    @await RenderSectionAsync("Styles", false)
</head>
<body>
    <div class="main-wrapper">

        <!-- partial:partials/_sidebar.html -->
        @await Html.PartialAsync("_Sidebar")
        <!-- partial -->

        <div class="page-wrapper">
            <!-- partial:partials/_navbar.html -->
            @await Html.PartialAsync("_Navbar")
            <!-- partial -->
            <div class="page-content">
                <nav class="page-breadcrumb">
                    <ol class="breadcrumb">

                        <li class="breadcrumb-item">
                            <h5>
                                @if (!string.IsNullOrEmpty(ViewBag.ModuleIcon))
                                {
                                    <i class="link-icon" data-feather="@ViewBag.ModuleIcon"></i>
                                }
                                <span>
                                    @ViewBag.ModuleName
                                </span>
                            </h5>
                        </li>

                    </ol>
                </nav>

                @RenderBody()

            </div>
            <!-- partial:partials/_footer.html -->
            <footer class="footer d-flex flex-column flex-md-row align-items-center justify-content-between px-4 py-3 border-top small">
                <p class="text-muted mb-1 mb-md-0">@_CommonLocalizer["Copyright"] © @DateTime.Now.Year <a href="https://www.nobleui.com" target="_blank">@_CommonLocalizer["CommonBoilerPlateEight"]</a>.</p>
                <p class="text-muted">Common World <i class="mb-1 text-primary ms-1 icon-sm" data-feather="heart"></i></p>
            </footer>
        </div>
    </div>

    <!-- core:js -->
    <script src="~/vendors/core/core.js"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/js/sweetalert.js"></script>
    <script src="~/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/vendors/datatables.net-bs5/datatables-bootstrap5.dist.js"></script>
    <script src="~/vendors/block-ui/block-ui.dist.js"></script>
    <script src="~/vendors/select2/js/select2.min.js"></script>
    <script src="~/vendors/flatpickr/flatpickr.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/vendors/feather-icons/feather.min.js"></script>
    <script src="~/js/template.js" asp-append-version="true"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/vendors/apexcharts/apexcharts.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- End custom js for this page -->
    @await Html.PartialAsync("_notificationPartial")
    @await RenderSectionAsync("Scripts", false)

</body>
</html>    

CommonBoilerPlateEight.Web/Views/Shared/_Navbar.cshtml
<nav class="navbar">
    <a href="#" class="sidebar-toggler">
        <i data-feather="menu"></i>
    </a>
    <div class="navbar-content">
        <ul class="navbar-nav">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="flag-icon flag-icon-@_CommonLocalizer["LanguageFlag"] mt-1" title="@_CommonLocalizer["Language"]"></i> <span class="ms-1 me-1 d-none d-md-inline-block">@_CommonLocalizer["Language"]</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="languageDropdown">
                    <a href="@Url.Action("SetCulture", "Base", new { culture = "en-US"})" class="dropdown-item py-2"><i class="flag-icon flag-icon-us" title="us" id="us"></i> <span class="ms-1"> English </span></a>
                    
                </div>
            </li>


            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="appsDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i data-feather="settings"></i>
                </a>
                <div class="dropdown-menu p-0" aria-labelledby="appsDropdown">

                    <ul class="list-unstyled p-1">
     
                        <li class="dropdown-item py-2" asp-authorize="Setting-Email">
                            <a asp-controller="Setting" asp-action="EmailSetup" class="text-body ms-0">
                                <i class="me-2 icon-md" data-feather="settings"></i>
                                <span>@_CommonLocalizer["EmailSetting"]</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="wd-30 ht-30 rounded-circle" src="/images/others/placeholder.jpg" alt="profile"> <span class="text-primary">@User.Identity.Name</span>
                </a>
                <div class="dropdown-menu p-0" aria-labelledby="profileDropdown">

                    <ul class="list-unstyled p-1">
                        <li class="dropdown-item py-2">
                            <a href="../../pages/general/profile.html" class="text-body ms-0">
                                <i class="me-2 icon-md" data-feather="user"></i>
                                <span>@_CommonLocalizer["Profile"]</span>
                            </a>
                        </li>
                        <li class="dropdown-item py-2">
                            <a href="#" class="text-body ms-0">
                                <i class="me-2 icon-md" data-feather="key"></i>
                                <span>@_CommonLocalizer["ChangePassword"]</span>
                            </a>
                        </li>
                        <li class="dropdown-item py-2">
                            <a asp-controller="Account" asp-action="Logout" class="text-body ms-0">
                                <i class="me-2 icon-md" data-feather="log-out"></i>
                                <span>@_CommonLocalizer["LogOut"]</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</nav>

CommonBoilerPlateEight.Web/Views/Shared/_PaginationPartial.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core

<style>
	.pagination {
		display: flex;
		justify-content: left;
		margin-top: 20px; /* Increase this value to add more space above */
	}

		.pagination a, .pagination span {
			margin: 0 5px;
			padding: 5px 10px;
			border: 1px solid #ddd;
			color: #007bff;
			text-decoration: none;
		}

			.pagination a:hover {
				background-color: #ddd;
			}

		.pagination .active span {
			background-color: #007bff;
			color: white;
			border: 1px solid #007bff;
		}

		.pagination .disabled span {
			color: #aaa;
		}
</style>
<div class="text-center">
    @{
        var pageList = new StaticPagedList<object>(Model.data, Model.PageNumber, Model.PageSize, Model.TotalItemCount);
    }
    @Html.PagedListPager(pageList, page => Url.Action("List", new { pageNo = page }), PagedListRenderOptions.PageNumbersOnly)
</div>

CommonBoilerPlateEight.Web/Views/Shared/_Sidebar.cshtml
<nav class="sidebar">
    <div class="sidebar-header">
        <a href="#" class="sidebar-brand">
            Common<span>World</span>
        </a>
        <div class="sidebar-toggler not-active">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <div class="sidebar-body">
        <ul class="nav">
            <li class="nav-item nav-category">Main</li>
            <li class="nav-item" active-when-controllers="Home" active-when-actions="Index">
                <a href="@Url.Action("Index", "Home")" class="nav-link">
                    <i class="link-icon" data-feather="box"></i>
                    <span class="link-title">@_CommonLocalizer["Home"]</span>
                </a>
            </li>


            <li class="nav-item nav-category">Modules</li>
           

            <li class="nav-item" active-when-controllers="Customer" active-when-actions="Index,Create,Edit">
                <a href="@Url.Action("Index", "Customer")" class="nav-link">
                    <i class="link-icon" data-feather="users"></i>
                    <span class="link-title">@_CommonLocalizer["Customer"]</span>
                </a>
            </li>

            <li class="nav-item" active-when-controllers="Users" active-when-actions="Index,Create,Edit">
                <a href="@Url.Action("Index", "Users")" class="nav-link">
                    <i class="link-icon" data-feather="users"></i>
                    <span class="link-title">@_CommonLocalizer["User"]</span>
                </a>
            </li>

            
            <li class="nav-item nav-category">Setups</li>

            <li class="nav-item" active-when-controllers="Role" active-when-actions="Index,Create,Edit">
                <a href="@Url.Action("Index", "Role")" class="nav-link">
                    <i class="link-icon" data-feather="globe"></i>
                    <span class="link-title">@_CommonLocalizer["Role"]</span>
                </a>
            </li>
             <li class="nav-item" active-when-controllers="Country" active-when-actions="Index">
                <a href="@Url.Action("Index", "Country")" class="nav-link">
                    <i class="link-icon" data-feather="globe"></i>
                    <span class="link-title">@_CommonLocalizer["Country"]</span>
                </a>
            </li>

            <li class="nav-item" active-when-controllers="Setting" active-when-actions="EmailSetup">
                <a href="@Url.Action("EmailSetup", "Setting")" class="nav-link">
                    <i class="link-icon" data-feather="mail"></i>
                    <span class="link-title">@_CommonLocalizer["EmailSetting"]</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

CommonBoilerPlateEight.Web/Views/Shared/_notificationPartial.cshtml
<script>
    var msg = @(TempData["Message"] != null ? Html.Raw(TempData["Message"]) : Html.Raw("undefined"));

    if (msg) {
        Swal.fire({
            icon: msg.status,
            html: msg.message,
            toast: true,
            position: 'top-right',
            showConfirmButton: false,
            timer: 3000,
            customClass: {
                popup: 'class-white'
            },
        });
        @(TempData["Message"] = null)
    }
</script>